import { expect, test } from '@playwright/test'

test('adds a catalog template and logs an injection', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /i understand/i }).click()
  await page.getByRole('button', { name: /open catalog/i }).click()
  await page.getByRole('button', { name: /browse catalog/i }).click()
  await page.getByRole('button', { name: /add to plan/i }).first().click()
  await page.getByRole('button', { name: /save plan/i }).click()
  await page.getByRole('button', { name: 'Today' }).click()
  await expect(page.getByRole('heading', { name: 'BPC-157' }).first()).toBeVisible()
  await page.getByRole('button', { name: /done/i }).first().click()
  await expect(page.getByText('Completed')).toBeVisible()
  await page.getByRole('button', { name: 'Calendar' }).click()
  const monthPicker = page.getByLabel('Month')
  await expect(monthPicker).toBeVisible()
  const currentMonth = await monthPicker.inputValue()
  await page.getByRole('button', { name: /next/i }).click()
  await expect(monthPicker).not.toHaveValue(currentMonth)
})
